version: "3"

services:
  streamlit:
    image: "sestevez/job-postings"
    build: "."
    volumes:
      - "./:/code"
    network_mode: "host"
    command: ["streamlit", "run", "--browser.serverAddress", "localhost", "gender_words.py"]
